version: '2'
services:
  unblockit-app:
    image: unblockit
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://unblockit-postgresql:5432/UnblockIT
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  unblockit-postgresql:
    extends:
      file: postgresql.yml
      service: unblockit-postgresql
